### ISSUE TITLE
createApp is not a function

### ISSUE THREAD

**Issue by ranjanngc** [antfu/vite-ssg#235] opened 2022-04-25 06:54 UTC
D:\Assemble\src\core-vue-app\src\vue-frontend-app\node_modules\vite-ssg\dist\chunks\build.cjs:173
  const { routes } = await createApp(false);
                           ^

TypeError: createApp is not a function
    at Object.build (D:\Assemble\src\core-vue-app\src\vue-frontend-app\node_modules\vite-ssg\dist\chunks\build.cjs:173:28)     
    at async Object.handler (D:\Assemble\src\core-vue-app\src\vue-frontend-app\node_modules\vite-ssg\dist\node\cli.cjs:25:3)   
PS D:\Assemble\src\core-vue-app\src\vue-frontend-app>

**Comment by untlsn** [comment] 2022-04-29 10:19
I had the same problem.
Change:
```js
const createApp = ViteSSG(/* Your config */);
export default createApp;
```
to:
```js
export const createApp = ViteSSG(/* Your config */);
```

**Comment by yankeeinlondon** [comment] 2022-10-06 23:31
I have this issue but I was already exporting `createApp` as a named variable in **main.ts**.

**Comment by yankeeinlondon** [comment] 2022-10-07 01:04
I believe the right solution is to include the following in your `vite.config.ts`:

```ts
  ssr: {
    // TODO: workaround until they support native ESM
    noExternal: ['workbox-window', /vue-i18n/],
  },
```

**Comment by antfu** [comment] 2024-03-28 09:33
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-03-28 09:33 UTC

**Comment by ninaismail** [comment] 2024-06-02 12:01
I have a similar problem:   
const { routes } = createApp(false);
                     ^
TypeError: createApp is not a function
    at build (file:///C:/laragon/www/AITS_website/vuejs1/node_modules/vite-ssg/dist/node.mjs:1001:22)
    at async Object.handler (file:///C:/laragon/www/AITS_website/vuejs1/node_modules/vite-ssg/dist/node/cli.mjs:34:5)

**Comment by ninaismail** [comment] 2024-06-02 12:12
I'm having a similar problem:  
 const { routes } = createApp(false);
                     ^
TypeError: createApp is not a function
    at build (file:///C:/laragon/www/AITS_website/vuejs1/node_modules/vite-ssg/dist/node.mjs:1001:22)
    at async Object.handler (file:///C:/laragon/www/AITS_website/vuejs1/node_modules/vite-ssg/dist/node/cli.mjs:34:5)

**Comment by Spacemin8** [comment] 2025-04-03 19:47
I'm trying to set up ssg with vite, react but I'm running into an issue when building my project. I'm using vite-ssg along with react-router-dom and react-helmet-async for handling SEO. Here's how I configured my Root component and createApp function:
```
import React from 'react';
import { BrowserRouter } from 'react-router-dom';
import { HelmetProvider } from 'react-helmet-async';
import { AuthProvider } from './components/AuthContext';
import App from './App';
import './index.css';
import { ViteSSG } from 'vite-ssg';

// Export the root component for SSG
export const Root = () => (
  <React.StrictMode>
    <BrowserRouter>
      <HelmetProvider>
        <AuthProvider>
          <App />
        </AuthProvider>
      </HelmetProvider>
    </BrowserRouter>
  </React.StrictMode>
);

export const createApp = ViteSSG(Root, {
  routes: [
    '/',
    '/about',
    '/contact',
    '/privacy',
    '/terms',
    '/cookies',
    '/careers',
    '/sitemap',
    '/results',
    '/seo-preview',
    '/admin',
    '/admin/login',
    '/agent/login',
    '/agent/register'
  ]
});

```

Error during build (`vite-ssg build`)👇
```
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
file:///D:/Projects/project-bolt-sb1-z41hhfky/project/node_modules/vite-ssg/dist/node.mjs:1001
  const { routes } = await createApp(false);
                           ^

TypeError: createApp is not a function
    at build (file:///D:/Projects/project-bolt-sb1-z41hhfky/project/node_modules/vite-ssg/dist/node.mjs:1001:28)
    at async Object.handler (file:///D:/Projects/project-bolt-sb1-z41hhfky/project/node_modules/vite-ssg/dist/node/cli.mjs:34:5)

Node.js v20.18.0
```


Any help or guidance would be greatly appreciated! Thanks in advance. 🙏🙏🙏
