### ISSUE TITLE
bug:unhead build error

### ISSUE THREAD

**Issue by censujiang** [antfu/vite-ssg#368] opened 2023-08-18 13:15 UTC
### Describe the bug

When I change @vueuse/head to unhead, ViteSSG Rendering error.

```
[vite-ssg] Critical CSS generation enabled via `critters`
file:///D:/git/mydocs/node_modules/vite-ssg/dist/node.mjs:1066
        throw new Error(`${gray("[vite-ssg]")} ${red(`Error on page: ${cyan(route)}`)}
              ^

Error: [vite-ssg] Error on page: /about
TypeError: head._popSideEffectQueue is not a function
    at renderDOMHead (file:///D:/git/mydocs/node_modules/@unhead/dom/dist/index.mjs:52:33)
    at async file:///D:/git/mydocs/node_modules/vite-ssg/dist/node.mjs:1052:11
    at async file:///D:/git/mydocs/node_modules/vite-ssg/dist/node.mjs:635:36
    at file:///D:/git/mydocs/node_modules/vite-ssg/dist/node.mjs:1066:15
    at async file:///D:/git/mydocs/node_modules/vite-ssg/dist/node.mjs:635:36

Node.js v18.17.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Reproduction

none

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 41.92 GB / 63.95 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.5.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.50)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by laizp** [comment] 2023-08-21 11:06
I got this error too, but when I downgrade `@unhead/vue` from 1.3.4 to 1.2.2, this error disappear.

**Comment by censujiang** [comment] 2023-08-22 12:31
> I got this error too, but when I downgrade `@unhead/vue` from 1.3.4 to 1.2.2, this error disappear.

I guess it may be caused by internal API changes, but it still depends on @antfu's investigation🤔

**Comment by antfu** [comment] 2023-08-22 21:57
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-08-22 21:57 UTC

**Comment by Zhengqbbb** [comment] 2023-08-24 02:50
Here : https://stackblitz.com/edit/github-ngu39o?file=package.json&view=editor&startScript=build
![CleanShot 2023-08-24 at 10 42 58@2x](https://github.com/antfu/vite-ssg/assets/40693636/a9ba3d05-7327-42a6-b613-6c1430c82d53)

**Comment by censujiang** [comment] 2023-08-24 13:29
> 这里：[https://stackblitz.com/edit/github-ngu39o?file= package.json&view=editor&startScript=build](https://stackblitz.com/edit/github-ngu39o?file=package.json&view=editor&startScript=build) ![CleanShot 2023-08-24 at 10 42 58@2x](https://user-images.githubusercontent.com/40693636/262845754-a9ba3d05-7327-42a6-b613-6c1430c82d53.png)

@antfu

**Comment by liyasthomas** [comment] 2023-09-05 18:39
I'm facing the same issue on "@unhead/vue": "^1.5.2", "vite-ssg": "^0.23.1".
```
Error: [vite-ssg] Error on page: /
TypeError: head._popSideEffectQueue is not a function
```
@censujiang were you able to fix this by any means?

**Comment by censujiang** [comment] 2023-09-06 12:27
> I'm facing the same issue on "@unhead/vue": "^1.5.2", "vite-ssg": "^0.23.1".
> 
> ```
> Error: [vite-ssg] Error on page: /
> TypeError: head._popSideEffectQueue is not a function
> ```
> 
> @censujiang were you able to fix this by any means?

nope
