### ISSUE TITLE
build output content has something like `["__file","/Users/xxxxx/workspace/www/src/pages/Home.vue"]`

### ISSUE THREAD

**Issue by airene** [antfu/vite-ssg#349] opened 2023-05-10 03:11 UTC
### Describe the bug

the file path is in production build output ,is ok?

### Reproduction

always show

### System Info

```Shell
no
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment] 2023-05-16 10:26
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2023-05-16 10:26 UTC

**Comment by foxxyz** [comment] 2023-07-01 19:07
@airene this was fixed in #356. I'm thankful you reported it because it motivated me to try and find the source of the bug 🙏🏽

**Comment by airene** [comment] 2023-07-02 16:18
great work! Thanks you too.
