### ISSUE TITLE
Build fails relating to UnoCSS, works on dev

### ISSUE THREAD

**Issue by davesierra** [antfu/vite-ssg#243] opened 2022-05-05 20:52 UTC
Hello, was encouraged to report via the message `[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues`

So after cloning vitesse and running it via `pnpm dev`, everything works fine.

I also used this as a starter template, so afterwards I've made a couple modifications; happy to provide details if needed.

However when I try to do `pnpm build`, I get an error.

Here is a paste of the exact error reported:
```
174 modules transformed.
rendering chunks (4)...[unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks,
this is likely an internal bug of unocss vite plugin

PWA v0.12.0
mode      generateSW
precache  5 entries (0.00 KiB)
files generated
  dist/sw.js
  dist/workbox-f51ab5e4.js
warnings
  One of the glob patterns doesn't match any files. Please remove or fix the following: {
  "globDirectory": "/Users/davesierra/Projects/companyname/projectname/dist",
  "globPattern": "**/*.{js,css,html}",
  "globIgnores": [
    "**/node_modules/**/*",
    "sw.js",
    "workbox-*.js"
  ]
}


[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
/Users/davesierra/Projects/companyname/projectname/node_modules/@unocss/vite/dist/index.cjs:306
          this.error(new Error("[unocss] does not found CSS placeholder in the generated chunks,\nthis is likely an internal bug of unocss vite plugin"));
                     ^

Error: [unocss] does not found CSS placeholder in the generated chunks,
this is likely an internal bug of unocss vite plugin
    at Object.generateBundle (/Users/davesierra/Projects/companyname/projectname/node_modules/@unocss/vite/dist/index.cjs:306:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bundle.generate (/Users/davesierra/Projects/companyname/projectname/node_modules/.pnpm/rollup@2.70.2/node_modules/rollup/dist/shared/rollup.js:16058:9)
    at async /Users/davesierra/Projects/companyname/projectname/node_modules/.pnpm/rollup@2.70.2/node_modules/rollup/dist/shared/rollup.js:23679:27
    at async catchUnfinishedHookActions (/Users/davesierra/Projects/companyname/projectname/node_modules/.pnpm/rollup@2.70.2/node_modules/rollup/dist/shared/rollup.js:23121:20)
    at async doBuild (/Users/davesierra/Projects/companyname/projectname/node_modules/.pnpm/vite@2.9.5/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:39185:20)
    at async Object.build (/Users/davesierra/Projects/companyname/projectname/node_modules/.pnpm/vite@2.9.5/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:39011:16)
    at async Object.build (/Users/davesierra/Projects/companyname/projectname/node_modules/vite-ssg/dist/chunks/build.cjs:135:3)
    at async Object.handler (/Users/davesierra/Projects/companyname/projectname/node_modules/vite-ssg/dist/node/cli.cjs:25:3) {
  code: 'PLUGIN_ERROR',
  plugin: 'unocss:global:build:generate',
  hook: 'generateBundle'
}

Node.js v17.6.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by userquin** [comment] 2022-05-07 09:57
@davesierra provide a minimal repro on github or stackblitz

**Comment by alvarosabu** [comment] 2022-08-01 15:05
I think this is an issue on the [@unocss/vite](https://github.com/unocss/unocss) package rather than this

**Comment by antfu** [comment] 2022-08-01 18:52
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2022-08-01 18:52 UTC
