### ISSUE TITLE
Hello, author. All the generated static pages open and the content becomes "not found".

### ISSUE THREAD

**Issue by jomywang** [antfu/vite-ssg#244] opened 2022-05-09 07:07 UTC
The page of .html cannot find the corresponding component in the routing table, and the content is replaced with [... All] Vue's content

**Comment by antfu** [comment] 2022-05-09 07:25
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by antfu** 2022-05-09 07:25 UTC

**Comment by jomywang** [comment] 2022-05-09 08:18
![1652084052(1)](https://user-images.githubusercontent.com/27123969/167368453-01867610-904e-41e5-b65d-724e1eb1966f.png)
sorry，After packaging according to your demo( npm run build), visit about.html, the result shown in the figure above is returned. He should be rendering about Vue's content is right

**Comment by userquin** [comment] 2022-05-09 08:45
@jomywang use route names, remove the .html extension and the vitesse context if you are not using base on vite config

**Comment by jomywang** [comment] 2022-05-09 10:21
Thank you. The route can be accessed normally. Can seo search the data on the page? I wonder when these static pages are used?

**Comment by userquin** [comment] 2022-05-09 10:28
@jomywang you can configure your server to provide the html page when requested the route name, for example, when requesting `/about` just forward the `/about.html` page content on the server and so on.

Check also vitesse repo (it is using `vite-ssg`) here https://github.com/antfu/vitesse : it is using `vite-ssg-sitemap`

**Comment by userquin** [comment] 2022-05-09 10:38
@jomywang check the response for previous repo for `/about` route here https://optimistic-cray-38ef22.netlify.app/about (previous repro deployed in that url)

**Comment by jomywang** [comment] 2022-05-10 02:04
Thank you. I see. In fact, the entry of the page is a route, not a packaged HTML file. Although the access is a route, the rendering is an HTML page, for example: https://optimistic-cray-38ef22.netlify.app/about In fact, the rendering content is https://optimistic-cray-38ef22.netlify.app/about.html 。 I've always been obsessed that the entry of the page is HTML file
